### PR TITLE
Fix wrong minimum GPU frequency settings

### PR DESCRIPTION
**Pull request by erayrafet**

### CODE REVIEW

**Comment by T1mpp4** [comment]
According to Huawei-provided files, the available frequencies are:

`120000000 180000000 240000000 288000000 360000000 480000000 600000000`

for gpu. Where did you figure that there is a typo?
These minimun (288000000->120000000) values should be updated in powerhal too, if correct.

**Comment by erayrafet** [comment]
From the stock kernel.

**Comment by erayrafet** [comment]
They are already updated in PowerHAL.

**Comment by T1mpp4** [comment]
No they're not updated.
I will not accept this until I figure out which value is the true minimum...
Some files tell different values. You are propaply correct but I wan't to make sure.

**Comment by erayrafet** [comment]
You can check /sys/devices/e8600000.mali/devfreq/gpufreq/available_frequencies.

**Comment by T1mpp4** [comment]
Yes, that is what I checked, but when looking at e.g. thermal files, the minimum is said to be 120000000.
I will look at this later as it's not mandatory at the moment.

**Comment by erayrafet** [comment]
Thermal files are wrong. This is the full GPU frequency range:
288000000 360000000 480000000 600000000 680000000

**Comment by T1mpp4** [comment]
Then it is. Thanks.

**Comment by erayrafet** [comment]
You're welcome.

**Pull request merged**
